# Setup and configure ruby things for reddit app
- name: "Reddit App: Configure app environment"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: Install ruby and rubygems and required packages
    apt: "name={{ item }} state=present"
    with_items:
      - ruby-full
      - ruby-dev
      - build-essential

  - name: Install Ruby bundler
    gem:
      name: bundler
      state: present
      user_install: no

# Setup and configure mongodb for reddit app
- name: "Reddit App: Install mongodb"
  hosts: all
  gather_facts: no
  become: true

  tasks:
  - name: Add apt-key for mongodb repo
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com
      id: EA312927
      state: present
  - name: Add mongodb repository
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
  - name: Install mongodb package
    apt:
      name: mongodb-org
      update_cache: yes
  - name: Add mongodb to systemd
    service: 
      name=mongod 
      state=started 
      daemon-reload=true

# Deploy reddit app
- name: "Reddit App: Deploy application"
  hosts: reddit_app
  gather_facts: no

  tasks:
  - name: Remove me after adding real things
    debug:
      msg: "В этом сценарии нужно добавить модули для деплоя приложения, после можно удалить вызов модуля debug, который выводит это сообщение"
